### PR TITLE
Implement new configurbles in TableReader + rename some process funct…

### PR DESCRIPTION
**Pull request by feisenhu**
…ions

In my latest [pull request in O2Physics](https://github.com/AliceO2Group/O2Physics/pull/1520) I have introduced some new configurables now used in the TableReader and also applied some renaming of some processFunctions.

In case the PR is merged, this PR would help to keep consistency of the interface.

### CODE REVIEW

**Comment by ctolon** [comment]
@feisenhu thanks for your reminder and update, I will also integrate the arguments and configurations for the CLI immediately

**Comment by feisenhu** [comment]
@ctolon I'm sorry that I didn't mentioned it but the above pull request is not merged yet.
So please make sure that it will not come to major conflicts.

This PR was meant to be merged after the other PR is merged so everything goes hand in hand.

In case Ionut will approve the other PR soon we might be able to keep it like that.

**Comment by ctolon** [comment]
@feisenhu  I see, then I'm reverting these changes for now, when these changes are merged in O2Physics, we can merge them here again. Thanks again

**Comment by feisenhu** [comment]
@ctolon The [pull request in O2Physics](https://github.com/AliceO2Group/O2Physics/pull/1520) is now merged.
So we can apply these changes again. Thank you very much.

**Comment by ctolon** [comment]
@feisenhu Thanks for letting me know, I'm re-applying the changes right away

**Pull request merged**
